apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # This storageClassName must be correct for your cluster storage solution
  storageClassName: gp2
